# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Charlie H. Kim
description: "Hi I'm Charlie and am passionate about efficiently employing business intelligence/data science tools and techniques to have real-world impacts. My portfolio focuses on illustrations of interesting projects I've undertaken over the years. Please visit my GitHub & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Virginia, US"
resume_url: /docs/Charlie_Kim_CV_202511.docx
avatar_image: /img/Charlie_Kim_photo_outdoor.jpg

#-------------------------------
# Contact links
linkedln: "https://linkedin.com/in/charlie-h-kim" # Add your linkedln handle
github: "https://stetson06.github.io"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/








