# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Charlie H. Kim
description: "Hi I'm Charlie and am passionate about efficiently employing tools and techniques across the entire business intelligence/data science spectrum to add business value. My portfolio contains summaries of some interesting projects I've undertaken over the years. Hope you enjoy them! Thanks to StackEdit for making it so easy to create the underlying Markdown language for each project. Please visit my GitHub & LinkedIn pages (or download my Resume) by using the links below."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: AI Engineering & Data Science <span style="color:#f58506"> Portfolio </span>
location: "Virginia, US"
resume_url: /docs/Charlie_Kim_CV_202511_Base.docx
avatar_image: /img/Charlie_Kim_photo_outdoor.jpg

#-------------------------------
# Contact links
linkedln: "https://linkedin.com/in/charlie-h-kim" # Add your linkedln handle
github: "https://stetson06.github.io"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/













